apiVersion: apps/v1
kind: Deployment
metadata:
  name: prj2-deployment
  labels:
    app: prj2-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prj2-app
  template:
    metadata:
      labels:
        app: prj2-app
    spec:
      containers:
      - name: prj2-container
        image: hbabudocker/prj2:latest
        ports:
        - containerPort: 3030
